version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: staging
  reviewers:
  - mrhallak
  assignees:
  - mrhallak
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: docker
  directory: "/services/airflow"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: staging
  reviewers:
  - mrhallak
  assignees:
  - mrhallak
- package-ecosystem: docker
  directory: "/services/elasticsearch"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: staging
  reviewers:
  - mrhallak
  assignees:
  - mrhallak
- package-ecosystem: docker
  directory: "/services/kibana"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: staging
  reviewers:
  - mrhallak
  assignees:
  - mrhallak
- package-ecosystem: docker
  directory: "/services/postgres"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: staging
  reviewers:
  - mrhallak
  assignees:
  - mrhallak
