version: '3'

services:
    airflow:
        restart: "always"
        build:
            context: .
            dockerfile: services/airflow/Dockerfile
        ports:
            - 8080:8080
        env_file: 
            - config/airflow.env
            - config/gcp.env
            - config/postgres.env
        volumes: 
            - ./src/:/usr/local/airflow/dags
        command: webserver

    jupyter:
        restart: "always"
        build:
            context: .
            dockerfile: services/jupyter/Dockerfile
        ports:
            - 8888:8888
        volumes:
            - ./src/:/home/jovyan/work/
        env_file:
            - config/jupyter.env
            - config/gcp.env
        entrypoint: sh -c 'start-notebook.sh --NotebookApp.token=$$JUPYTER_PASSWORD'

    portainer:
        restart: "always"
        build:
            context: .
            dockerfile: services/portainer/Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_volume:/data
        ports:
            - 9090:9000
        command: -H unix:///var/run/docker.sock

    superset:
        restart: "always"
        build:
            context: .
            dockerfile: services/superset/Dockerfile
        ports:
            - 8088:8088
        env_file:
            - config/superset.env

    postgres:
        restart: "always"
        build:
            context: .
            dockerfile: services/postgres/Dockerfile
        env_file:
            - config/postgres.env
        volumes:
            - postgres_volume:/var/lib/postgresql/data/
            - ./services/postgres/:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432


volumes:
    portainer_volume:
    postgres_volume: