version: '3'

services:
    airflow:
        restart: "always"
        depends_on:
          - postgres
          - elasticsearch
        build:
            context: .
            dockerfile: services/airflow/Dockerfile
        ports:
            - 8080:8080
        env_file: 
            - config/airflow.env
        volumes: 
            - .:/usr/local/airflow/dags
        command: webserver

    portainer:
        restart: "always"
        build:
            context: .
            dockerfile: services/portainer/Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_volume:/data
        ports:
            - 9090:9000
        command: -H unix:///var/run/docker.sock

    elasticsearch:
        restart: "always"
        build:
            context: .
            dockerfile: services/elasticsearch/Dockerfile
        env_file:
            - config/elasticsearch.env
        ports:
            - 9200:9200
            - 9300:9300
    
    kibana:
        restart: "always"
        build:
            context: .
            dockerfile: services/kibana/Dockerfile
        ports:
            - 5601:5601
        env_file:
            - config/kibana.env

    postgres:
        restart: "always"
        image: postgres
        ports:
            - 5432:5432
        env_file:
          - config/postgres.env

volumes:
    postgres_volume:
    portainer_volume: