on:
  push:
    branches:
    - master
    - staging
  pull_request:
    branches:
    - master
    - staging

name: Build Docker-Compose

jobs:
  docker:
    name: Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image
      run: |
        docker-compose -f docker-compose.yml build
