name: Test workflow

on:
  pull_request:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Pull master
        uses: actions/checkout@master

      - name: Setup Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          directory: ./coverage/reports/
          name: coronalytics-codecov
          fail_ci_if_error: true
